### ISSUE TITLE
nokogiri 1.13 breaks fog-xml install on some OS

### ISSUE THREAD

**Issue by dann1** [fog/fog-xml#22]
I was trying to install fog-opennebula which lists fog-xml as a dependency on the gempsec. I ran into this error

```
[root@c8-minione6 ~]# echo $GEM_NAME
fog-opennebula
[root@c8-minione6 ~]# gem install --install-dir /usr/share/one/gems/ --bindir /usr/share/one/gems/bin/ --no-document --conservative $GEM_NAME
Building native extensions. This could take a while...
Successfully installed racc-1.6.0
Fetching: nokogiri-1.13.0-x86_64-linux.gem (100%)
ERROR:  Error installing fog-opennebula:
	nokogiri requires Ruby version < 3.2.dev, >= 2.6. The current ruby version is 2.5.0.
```

on nokogiri page there is a release on [Jan 6th](https://github.com/sparklemotion/nokogiri/releases/tag/v1.13.0) which ends support for ruby 2.5

> This release ends support for:
Ruby 2.5, for which official support ended 2021-03-31.

which is the one that centos8 and ubuntu1804 use by default.

Now looking at fog-xml gemspec there is [this line](https://github.com/fog/fog-xml/blob/f2fd04158d62dd5a3c2b69bdfd3e15acf373a285/fog-xml.gemspec#L28) that could be updated to <= 1.12 on a specific version so that it doesn't break on these OS. 

Would that be possible ?

**Comment by geemus** [comment]
Hmm. My preference would be for both those who are able to get and use newer versions, and for those with old versions to have things still work. For instance, I think you could use bundler and have a gemfile that specified an earlier version of nokogiri and it would (I think) resolve things properly. Is that tenable for you?

**Comment by dann1** [comment]
Hello, I have [fixed](https://github.com/fog/fog-opennebula/blob/master/fog-opennebula.gemspec#L27) the nokogiri version dependency on the fog-opennebula provider. The issue is that OpenNebula still supports OS that run ruby <2.6. This is gonna be a temporary solution until the support for such OSes is deprecated. The issue can be closed.

**Comment by geemus** [comment]
Alright, sounds like a plan, thanks.
