### ISSUE TITLE
Push to rubygems.org?

### ISSUE THREAD

**Issue by axlekb** [fog/fog-xml#8]
Hi folks,
  Looks like you've relaxed the `nokogiri` dependencies in `master`.  Can you tag it and push a new version to rubygems.org because `0.1.2` is still `nokogiri ~> 1.5` ?

https://rubygems.org/gems/fog-xml

**Comment by axlekb** [comment]
Nevermind.  Not my issue.  Sorry!

**Comment by geemus** [comment]
Thanks for the update, just let me know if I need to push this at some point (it wasn't really on my radar to, but can certainly do so if needed). Thanks!
